# Generated by Django 5.1.1 on 2024-09-19 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.TextField()),
                ('rating', models.CharField(max_length=5)),
                ('released', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.TextField()),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('awards', models.TextField()),
                ('poster', models.TextField()),
                ('metascore', models.TextField()),
                ('imdb_rating', models.TextField()),
                ('imdb_votes', models.TextField()),
                ('imdb_id', models.TextField()),
                ('type', models.TextField()),
                ('dvd', models.TextField()),
                ('box_office', models.TextField()),
                ('production', models.TextField()),
                ('website', models.TextField()),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ratings')),
            ],
        ),
    ]
