# Generated by Django 5.1.1 on 2024-09-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='released',
            field=models.DateTimeField(),
        ),
    ]
