# Generated by Django 5.1.1 on 2024-09-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='released',
            field=models.DateTimeField(null=True),
        ),
    ]
