# Generated by Django 5.1.1 on 2024-09-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_actors_alter_movies_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
