# Generated by Django 5.1.1 on 2024-09-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movies_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='ratings',
        ),
        migrations.AddField(
            model_name='ratings',
            name='ratings_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movies'),
        ),
    ]
