# Generated by Django 5.1.1 on 2024-09-19 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movies_ratings_ratings_ratings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='ratings_id',
        ),
        migrations.AddField(
            model_name='ratings',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movies'),
        ),
    ]
