# Generated by Django 5.1.1 on 2024-09-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_ratings_ratings_id_ratings_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cookie_id',
            field=models.TextField(null=True),
        ),
    ]
