# Generated by Django 5.1.1 on 2024-09-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_imdb_id_movies_imbd_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='imbd_rating',
            new_name='imdb_rating',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='imbd_votes',
            new_name='imdb_votes',
        ),
    ]
